// Country code mapping with ISO codes
export const countryCodeMap = {
  AF: { name: 'Afghanistan', id: 4 },
  AL: { name: 'Albania', id: 8 },
  DZ: { name: 'Algeria', id: 12 },
  AS: { name: 'American Samoa', id: 16 },
  AD: { name: 'Andorra', id: 20 },
  AO: { name: 'Angola', id: 24 },
  AI: { name: 'Anguilla', id: 660 },
  AQ: { name: 'Antarctica', id: 10 },
  AG: { name: 'Antigua and Barbuda', id: 28 },
  AR: { name: 'Argentina', id: 32 },
  AM: { name: 'Armenia', id: 51 },
  AW: { name: 'Aruba', id: 533 },
  AU: { name: 'Australia', id: 36 },
  AT: { name: 'Austria', id: 40 },
  AZ: { name: 'Azerbaijan', id: 31 },
  BS: { name: 'Bahamas', id: 44 },
  BH: { name: 'Bahrain', id: 48 },
  BD: { name: 'Bangladesh', id: 50 },
  BB: { name: 'Barbados', id: 52 },
  BY: { name: 'Belarus', id: 112 },
  BE: { name: 'Belgium', id: 56 },
  BZ: { name: 'Belize', id: 84 },
  BJ: { name: 'Benin', id: 204 },
  BM: { name: 'Bermuda', id: 60 },
  BT: { name: 'Bhutan', id: 64 },
  BO: { name: 'Bolivia', id: 68 },
  BQ: { name: 'Bonaire, Sint Eustatius and Saba', id: 535 },
  BA: { name: 'Bosnia and Herzegovina', id: 70 },
  BW: { name: 'Botswana', id: 72 },
  BV: { name: 'Bouvet Island', id: 74 },
  BR: { name: 'Brazil', id: 76 },
  IO: { name: 'British Indian Ocean Territory', id: 86 },
  BN: { name: 'Brunei Darussalam', id: 96 },
  BG: { name: 'Bulgaria', id: 100 },
  BF: { name: 'Burkina Faso', id: 854 },
  BI: { name: 'Burundi', id: 108 },
  CV: { name: 'Cabo Verde', id: 132 },
  KH: { name: 'Cambodia', id: 116 },
  CM: { name: 'Cameroon', id: 120 },
  CA: { name: 'Canada', id: 124 },
  KY: { name: 'Cayman Islands', id: 136 },
  CF: { name: 'Central African Republic', id: 140 },
  TD: { name: 'Chad', id: 148 },
  CL: { name: 'Chile', id: 152 },
  CN: { name: 'China', id: 156 },
  CX: { name: 'Christmas Island', id: 162 },
  CC: { name: 'Cocos (Keeling) Islands', id: 166 },
  CO: { name: 'Colombia', id: 170 },
  KM: { name: 'Comoros', id: 174 },
  CG: { name: 'Congo', id: 178 },
  CD: { name: 'Congo (Democratic Republic of the)', id: 180 },
  CK: { name: 'Cook Islands', id: 184 },
  CR: { name: 'Costa Rica', id: 188 },
  HR: { name: 'Croatia', id: 191 },
  CU: { name: 'Cuba', id: 192 },
  CW: { name: 'Curaçao', id: 531 },
  CY: { name: 'Cyprus', id: 196 },
  CZ: { name: 'Czechia', id: 203 },
  DK: { name: 'Denmark', id: 208 },
  DJ: { name: 'Djibouti', id: 262 },
  DM: { name: 'Dominica', id: 212 },
  DO: { name: 'Dominican Republic', id: 214 },
  EC: { name: 'Ecuador', id: 218 },
  EG: { name: 'Egypt', id: 818 },
  SV: { name: 'El Salvador', id: 222 },
  GQ: { name: 'Equatorial Guinea', id: 226 },
  ER: { name: 'Eritrea', id: 232 },
  EE: { name: 'Estonia', id: 233 },
  SZ: { name: 'Eswatini', id: 748 },
  ET: { name: 'Ethiopia', id: 231 },
  FK: { name: 'Falkland Islands (Malvinas)', id: 238 },
  FO: { name: 'Faroe Islands', id: 234 },
  FJ: { name: 'Fiji', id: 242 },
  FI: { name: 'Finland', id: 246 },
  FR: { name: 'France', id: 250 },
  GF: { name: 'French Guiana', id: 254 },
  PF: { name: 'French Polynesia', id: 258 },
  TF: { name: 'French Southern Territories', id: 260 },
  GA: { name: 'Gabon', id: 266 },
  GM: { name: 'Gambia', id: 270 },
  GE: { name: 'Georgia', id: 268 },
  DE: { name: 'Germany', id: 276 },
  GH: { name: 'Ghana', id: 288 },
  GI: { name: 'Gibraltar', id: 292 },
  GR: { name: 'Greece', id: 300 },
  GL: { name: 'Greenland', id: 304 },
  GD: { name: 'Grenada', id: 308 },
  GP: { name: 'Guadeloupe', id: 312 },
  GU: { name: 'Guam', id: 316 },
  GT: { name: 'Guatemala', id: 320 },
  GG: { name: 'Guernsey', id: 831 },
  GN: { name: 'Guinea', id: 324 },
  GW: { name: 'Guinea-Bissau', id: 624 },
  GY: { name: 'Guyana', id: 328 },
  HT: { name: 'Haiti', id: 332 },
  HM: { name: 'Heard Island and McDonald Islands', id: 334 },
  VA: { name: 'Holy See', id: 336 },
  HN: { name: 'Honduras', id: 340 },
  HK: { name: 'Hong Kong', id: 344 },
  HU: { name: 'Hungary', id: 348 },
  IS: { name: 'Iceland', id: 352 },
  IN: { name: 'India', id: 356 },
  ID: { name: 'Indonesia', id: 360 },
  IR: { name: 'Iran', id: 364 },
  IQ: { name: 'Iraq', id: 368 },
  IE: { name: 'Ireland', id: 372 },
  IM: { name: 'Isle of Man', id: 833 },
  IL: { name: 'Israel', id: 376 },
  IT: { name: 'Italy', id: 380 },
  JM: { name: 'Jamaica', id: 388 },
  JP: { name: 'Japan', id: 392 },
  JE: { name: 'Jersey', id: 832 },
  JO: { name: 'Jordan', id: 400 },
  KZ: { name: 'Kazakhstan', id: 398 },
  KE: { name: 'Kenya', id: 404 },
  KI: { name: 'Kiribati', id: 296 },
  KP: { name: "Korea (Democratic People's Republic of)", id: 408 },
  KR: { name: 'South Korea', id: 410 },
  KW: { name: 'Kuwait', id: 414 },
  KG: { name: 'Kyrgyzstan', id: 417 },
  LA: { name: "Lao People's Democratic Republic", id: 418 },
  LV: { name: 'Latvia', id: 428 },
  LB: { name: 'Lebanon', id: 422 },
  LS: { name: 'Lesotho', id: 426 },
  LR: { name: 'Liberia', id: 430 },
  LY: { name: 'Libya', id: 434 },
  LI: { name: 'Liechtenstein', id: 438 },
  LT: { name: 'Lithuania', id: 440 },
  LU: { name: 'Luxembourg', id: 442 },
  MO: { name: 'Macao', id: 446 },
  MG: { name: 'Madagascar', id: 450 },
  MW: { name: 'Malawi', id: 454 },
  MY: { name: 'Malaysia', id: 458 },
  MV: { name: 'Maldives', id: 462 },
  ML: { name: 'Mali', id: 466 },
  MT: { name: 'Malta', id: 470 },
  MQ: { name: 'Martinique', id: 474 },
  MR: { name: 'Mauritania', id: 478 },
  MU: { name: 'Mauritius', id: 480 },
  YT: { name: 'Mayotte', id: 175 },
  MX: { name: 'Mexico', id: 484 },
  FM: { name: 'Micronesia', id: 583 },
  MD: { name: 'Moldova', id: 498 },
  MC: { name: 'Monaco', id: 492 },
  MN: { name: 'Mongolia', id: 496 },
  ME: { name: 'Montenegro', id: 499 },
  MS: { name: 'Montserrat', id: 500 },
  MA: { name: 'Morocco', id: 504 },
  MZ: { name: 'Mozambique', id: 508 },
  MM: { name: 'Myanmar', id: 104 },
  NA: { name: 'Namibia', id: 516 },
  NR: { name: 'Nauru', id: 520 },
  NP: { name: 'Nepal', id: 524 },
  NL: { name: 'Netherlands', id: 528 },
  NC: { name: 'New Caledonia', id: 540 },
  NZ: { name: 'New Zealand', id: 554 },
  NI: { name: 'Nicaragua', id: 558 },
  NE: { name: 'Niger', id: 562 },
  NG: { name: 'Nigeria', id: 566 },
  NU: { name: 'Niue', id: 570 },
  NF: { name: 'Norfolk Island', id: 574 },
  MP: { name: 'Northern Mariana Islands', id: 580 },
  NO: { name: 'Norway', id: 578 },
  OM: { name: 'Oman', id: 512 },
  PK: { name: 'Pakistan', id: 586 },
  PW: { name: 'Palau', id: 585 },
  PS: { name: 'Palestine, State of', id: 275 },
  PA: { name: 'Panama', id: 591 },
  PG: { name: 'Papua New Guinea', id: 598 },
  PY: { name: 'Paraguay', id: 600 },
  PE: { name: 'Peru', id: 604 },
  PH: { name: 'Philippines', id: 608 },
  PN: { name: 'Pitcairn', id: 612 },
  PL: { name: 'Poland', id: 616 },
  PT: { name: 'Portugal', id: 620 },
  PR: { name: 'Puerto Rico', id: 630 },
  QA: { name: 'Qatar', id: 634 },
  RO: { name: 'Romania', id: 642 },
  RU: { name: 'Russian Federation', id: 643 },
  RW: { name: 'Rwanda', id: 646 },
  RE: { name: 'Réunion', id: 638 },
  BL: { name: 'Saint Barthélemy', id: 652 },
  SH: { name: 'Saint Helena, Ascension and Tristan da Cunha', id: 654 },
  KN: { name: 'Saint Kitts and Nevis', id: 659 },
  LC: { name: 'Saint Lucia', id: 662 },
  MF: { name: 'Saint Martin (French part)', id: 663 },
  PM: { name: 'Saint Pierre and Miquelon', id: 666 },
  VC: { name: 'Saint Vincent and the Grenadines', id: 670 },
  WS: { name: 'Samoa', id: 882 },
  SM: { name: 'San Marino', id: 674 },
  ST: { name: 'Sao Tome and Principe', id: 678 },
  SA: { name: 'Saudi Arabia', id: 682 },
  SN: { name: 'Senegal', id: 686 },
  RS: { name: 'Serbia', id: 688 },
  SC: { name: 'Seychelles', id: 690 },
  SL: { name: 'Sierra Leone', id: 694 },
  SG: { name: 'Singapore', id: 702 },
  SX: { name: 'Sint Maarten (Dutch part)', id: 534 },
  SK: { name: 'Slovakia', id: 703 },
  SI: { name: 'Slovenia', id: 705 },
  SB: { name: 'Solomon Islands', id: 90 },
  SO: { name: 'Somalia', id: 706 },
  ZA: { name: 'South Africa', id: 710 },
  GS: { name: 'South Georgia and the South Sandwich Islands', id: 239 },
  SS: { name: 'South Sudan', id: 728 },
  ES: { name: 'Spain', id: 724 },
  LK: { name: 'Sri Lanka', id: 144 },
  SD: { name: 'Sudan', id: 736 },
  SR: { name: 'Suriname', id: 740 },
  SJ: { name: 'Svalbard and Jan Mayen', id: 744 },
  SE: { name: 'Sweden', id: 752 },
  CH: { name: 'Switzerland', id: 756 },
  SY: { name: 'Syrian Arab Republic', id: 760 },
  TW: { name: 'Taiwan', id: 158 },
  TJ: { name: 'Tajikistan', id: 762 },
  TZ: { name: 'Tanzania, United Republic of', id: 834 },
  TH: { name: 'Thailand', id: 764 },
  TL: { name: 'Timor-Leste', id: 626 },
  TG: { name: 'Togo', id: 768 },
  TK: { name: 'Tokelau', id: 772 },
  TO: { name: 'Tonga', id: 776 },
  TT: { name: 'Trinidad and Tobago', id: 780 },
  TN: { name: 'Tunisia', id: 788 },
  TR: { name: 'Turkey', id: 792 },
  TM: { name: 'Turkmenistan', id: 795 },
  TC: { name: 'Turks and Caicos Islands', id: 796 },
  TV: { name: 'Tuvalu', id: 798 },
  UG: { name: 'Uganda', id: 800 },
  UA: { name: 'Ukraine', id: 804 },
  AE: { name: 'United Arab Emirates', id: 784 },
  GB: { name: ['United Kingdom', 'UK'], id: 826 },
  US: { name: ['United States of America', 'USA', 'United States'], id: 840 },
  UY: { name: 'Uruguay', id: 858 },
  UZ: { name: 'Uzbekistan', id: 860 },
  VU: { name: 'Vanuatu', id: 548 },
  VE: { name: 'Venezuela (Bolivarian Republic of)', id: 862 },
  VN: { name: 'Viet Nam', id: 704 },
  VG: { name: 'Virgin Islands (British)', id: 92 },
  VI: { name: 'Virgin Islands (U.S.)', id: 850 },
  WF: { name: 'Wallis and Futuna', id: 876 },
  EH: { name: 'Western Sahara', id: 732 },
  YE: { name: 'Yemen', id: 887 },
  ZM: { name: 'Zambia', id: 894 },
  ZW: { name: 'Zimbabwe', id: 716 },
};

// Create a reverse lookup map (country name → countryCode)
export const countryNameToCodeMap = {};
Object.entries(countryCodeMap).forEach(([code, data]) => {
  if (Array.isArray(data.name)) {
    data.name.forEach((name) => {
      countryNameToCodeMap[name.toLowerCase()] = code;
    });
  } else {
    countryNameToCodeMap[data.name.toLowerCase()] = code;
  }
});
