export default {
  name: "user",
  type: "document",
  title: "User",
  fields: [
    {
      name: "username",
      title: "Username",
      type: "string",
      required: true,
    },
    {
      name: "name",
      title: "Name",
      type: "string",
      required: true,
    },
    {
      name: "handle",
      title: "Handle",
      type: "string",
    },
    {
      name: "avatar",
      title: "Avatar",
      type: "image",
    },
    {
      name: "isDominion",
      title: "Dominion Member",
      type: "boolean",
    },
    {
      name: "dominionSince",
      title: "Dominion Since",
      type: "date",
    },
    {
      name: "publicProfile",
      title: "Public Profile",
      type: "boolean",
    },
    {
      name: "quote", // this is the old field
      title: "Quote",
      type: "blockContent",
    },
    {
      type: "object", // this is the new field
      name: "cityContext",
      title: "City Context",
      options: {
        collapsible: true,
        collapsed: true,
      },
      fields: [
        {
          name: "quote",
          title: "Quote",
          type: "blockContent",
        },
        {
          name: "country",
          title: "Country",
          type: "string",
          options: {
            list: [
              "AF",
              "AX",
              "AL",
              "DZ",
              "AS",
              "AD",
              "AO",
              "AI",
              "AQ",
              "AG",
              "AR",
              "AM",
              "AW",
              "AU",
              "AT",
              "AZ",
              "BS",
              "BH",
              "BD",
              "BB",
              "BY",
              "BE",
              "BZ",
              "BJ",
              "BM",
              "BT",
              "BO",
              "BQ",
              "BA",
              "BW",
              "BV",
              "BR",
              "IO",
              "BN",
              "BG",
              "BF",
              "BI",
              "CV",
              "KH",
              "CM",
              "CA",
              "KY",
              "CF",
              "TD",
              "CL",
              "CN",
              "CX",
              "CC",
              "CO",
              "KM",
              "CD",
              "CG",
              "CK",
              "CR",
              "CI",
              "HR",
              "CU",
              "CW",
              "CY",
              "CZ",
              "DK",
              "DJ",
              "DM",
              "DO",
              "EC",
              "EG",
              "SV",
              "GQ",
              "ER",
              "EE",
              "ET",
              "FK",
              "FO",
              "FJ",
              "FI",
              "FR",
              "GF",
              "PF",
              "TF",
              "GA",
              "GM",
              "GE",
              "DE",
              "GH",
              "GI",
              "GR",
              "GL",
              "GD",
              "GP",
              "GU",
              "GT",
              "GG",
              "GN",
              "GW",
              "GY",
              "HT",
              "HM",
              "VA",
              "HN",
              "HK",
              "HU",
              "IS",
              "IN",
              "ID",
              "IR",
              "IQ",
              "IE",
              "IM",
              "IL",
              "IT",
              "JM",
              "JP",
              "JE",
              "JO",
              "KZ",
              "KE",
              "KI",
              "KP",
              "KR",
              "KW",
              "KG",
              "LA",
              "LV",
              "LB",
              "LS",
              "LR",
              "LY",
              "LI",
              "LT",
              "LU",
              "MO",
              "MK",
              "MG",
              "MW",
              "MY",
              "MV",
              "ML",
              "MT",
              "MH",
              "MQ",
              "MR",
              "MU",
              "YT",
              "MX",
              "FM",
              "MD",
              "MC",
              "MN",
              "ME",
              "MS",
              "MA",
              "MZ",
              "MM",
              "NA",
              "NR",
              "NP",
              "NL",
              "NC",
              "NZ",
              "NI",
              "NE",
              "NG",
              "NU",
              "NF",
              "MP",
              "NO",
              "OM",
              "PK",
              "PW",
              "PS",
              "PA",
              "PG",
              "PY",
              "PE",
              "PH",
              "PN",
              "PL",
              "PT",
              "PR",
              "QA",
              "RE",
              "RO",
              "RU",
              "RW",
              "BL",
              "SH",
              "KN",
              "LC",
              "MF",
              "PM",
              "VC",
              "WS",
              "SM",
              "ST",
              "SA",
              "SN",
              "RS",
              "SC",
              "SL",
              "SG",
              "SX",
              "SK",
              "SI",
              "SB",
              "SO",
              "ZA",
              "GS",
              "SS",
              "ES",
              "LK",
              "SD",
              "SR",
              "SJ",
              "SZ",
              "SE",
              "CH",
              "SY",
              "TW",
              "TJ",
              "TZ",
              "TH",
              "TL",
              "TG",
              "TK",
              "TO",
              "TT",
              "TN",
              "TR",
              "TM",
              "TC",
              "TV",
              "UG",
              "UA",
              "AE",
              "GB",
              "US",
              "UM",
              "UY",
              "UZ",
              "VU",
              "VE",
              "VN",
              "VG",
              "VI",
              "WF",
              "EH",
              "YE",
              "ZM",
              "ZW",
            ],
          },
        },
        {
          name: "city",
          title: "City",
          type: "string",
        },
      ],
    },
    {
      title: "Tags",
      name: "tags",
      type: "array",
      of: [{ type: "string" }],
      options: {
        layout: "tags",
      },
    },
    {
      type: "object",
      name: "address",
      title: "Address",
      options: {
        collapsible: true,
        collapsed: true,
      },
      fields: [
        {
          name: "line1",
          title: "Line 1",
          type: "string",
        },
        {
          name: "line2",
          title: "Line 2",
          type: "string",
        },
        {
          name: "city",
          title: "City",
          type: "string",
        },
        {
          name: "postal_code",
          title: "Postcode",
          type: "string",
        },
        {
          name: "state",
          title: "State",
          type: "string",
        },
        {
          name: "country",
          title: "Country",
          type: "string",
        },
      ],
    },
    {
      title: "Notifications",
      name: "notifications",
      type: "array",
      of: [
        {
          title: "Notification",
          type: "object",
          fields: [
            {
              title: "Title",
              name: "title",
              type: "string",
            },
            {
              title: "Body",
              name: "body",
              type: "blockContent",
            },
            {
              title: "Has Opened",
              name: "hasOpened",
              type: "boolean",
            },
            {
              title: "Notification Type",
              name: "notificationType",
              type: "string",
              readOnly: true,
            },
            {
              title: "Created",
              name: "created",
              type: "datetime",
              readOnly: true,
            },
          ],
        },
      ],
    },
    {
      name: "discordId",
      title: "Discord ID",
      type: "string",
      required: true,
    },
    {
      name: "stripeCustomerId",
      title: "Stripe Customer ID",
      type: "string",
      required: true,
    },
    {
      name: "salt",
      title: "Salt",
      type: "string",
      required: true,
    },
    {
      name: "hash",
      title: "Hash",
      type: "string",
      required: true,
    },
  ],
  orderings: [
    {
      title: "Name",
      name: "author",
      by: [{ field: "author", direction: "desc" }],
    },
  ],
  preview: {
    select: {
      name: "name",
      dominionSince: "dominionSince",
      isDominionWiteList: "isDominionWiteList",
      avatar: "avatar",
    },
    prepare(selection) {
      console.log("selection", selection);
      const { name, dominionSince, isDominionWiteList, avatar } = selection;
      return {
        title: name,
        subtitle: `
          ${dominionSince ? `Dominion. ` : ""}
          ${isDominionWiteList ? `White Listed. ` : ""}
        `,
        media: avatar,
      };
    },
  },
};
